import { User } from './types';

export const mockUser: User = {
  id: 'u1',
  name: 'Maxance',
  email: 'test@mail.com',
};


export const mockMovies = [
  {
    adult: false,
    backdrop_path: '/ebyxeBh56QNXxSJgTnmz7fXAlwk.jpg',
    genre_ids: [28, 878, 12],
    id: 1242898,
    original_language: 'en',
    original_title: 'Predator: Badlands',
    overview:
      'Cast out from his clan, a young Predator finds an unlikely ally in a damaged android and embarks on a treacherous journey in search of the ultimate adversary.',
    popularity: 420.2485,
    poster_path: '/pHpq9yNUIo6aDoCXEBzjSolywgz.jpg',
    release_date: '2025-11-05',
    title: 'Predator: Badlands',
    video: false,
    vote_average: 7.796,
    vote_count: 1491,
  },
  {
    adult: false,
    backdrop_path: '/gQimJqYMKCkwHIo8wwYKhmnCfBr.jpg',
    genre_ids: [28, 80, 53],
    id: 1242501,
    original_language: 'en',
    original_title: 'Icefall',
    overview:
      'A young Indigenous game warden arrests an infamous poacher only to discover that the poacher knows the location of a plane carrying millions of dollars that has crashed in a frozen lake. When a group of criminals and dirty cops are alerted to the poacher’s whereabouts, the warden and the poacher team up to fight back and escape across the treacherous lake before the ice melts.',
    popularity: 291.7639,
    poster_path: '/5Byv6nznAb2Izd0gHpODOXnuSbo.jpg',
    release_date: '2025-10-16',
    title: 'Icefall',
    video: false,
    vote_average: 6.542,
    vote_count: 84,
  },
  {
    adult: false,
    backdrop_path: '/kwNIQW7egAmI66sb0zIugMbpCfU.jpg',
    genre_ids: [28, 53, 80, 18, 9648],
    id: 1306368,
    original_language: 'en',
    original_title: 'The Rip',
    overview:
      'Trust frays when a team of Miami cops discovers millions in cash inside a run-down stash house, calling everyone — and everything — into question.',
    popularity: 291.2808,
    poster_path: '/p4bW2sJKAwcHuLpfoZK7Zo63osA.jpg',
    release_date: '2026-01-13',
    title: 'The Rip',
    video: false,
    vote_average: 7.148,
    vote_count: 294,
  },
  {
    adult: false,
    backdrop_path: '/vMxOmgmBGegjVObjlb8ugsjGgkD.jpg',
    genre_ids: [10752, 28, 18],
    id: 1252037,
    original_language: 'de',
    original_title: 'Der Tiger',
    overview:
      "A German Tiger tank crew is sent on a dangerous mission to rescue the missing officer Paul von Hardenburg from a top-secret bunker behind enemy lines. As they make their way through the lethal no-man's land, they must confront not only the enemy, but also their own fears and inner demons. Fueled by the Wehrmacht's methamphetamine, their mission increasingly becomes a journey into the heart of darkness.",
    popularity: 187.6576,
    poster_path: '/65Jr1JAgWlu9em8zHhAfrNJJQBt.jpg',
    release_date: '2025-09-18',
    title: 'The Tank',
    video: false,
    vote_average: 7.013,
    vote_count: 237,
  },
  {
    adult: false,
    backdrop_path: '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
    genre_ids: [16, 28, 14],
    id: 1311031,
    original_language: 'ja',
    original_title: '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
    overview:
      'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
    popularity: 127.4235,
    poster_path: '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
    release_date: '2025-07-18',
    title: 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
    video: false,
    vote_average: 7.6,
    vote_count: 662,
  },
  {
    adult: false,
    backdrop_path: '/oIJjO1CvEdTMFNkWfHaV0RB584G.jpg',
    genre_ids: [28, 80, 53],
    id: 628847,
    original_language: 'en',
    original_title: 'Trap House',
    overview:
      "An undercover DEA agent and his partner embark on a game of cat and mouse with an audacious, and surprising group of thieves - their own rebellious teenagers, who have begun robbing from a dangerous cartel, using their parents' tactics and top-secret intel to do it.",
    popularity: 120.4269,
    poster_path: '/6tpAPeuuqbVnYWWPoOLEDLSBU7a.jpg',
    release_date: '2025-11-14',
    title: 'Trap House',
    video: false,
    vote_average: 6.525,
    vote_count: 160,
  },
  {
    adult: false,
    backdrop_path: '/wCwZ4ljSsWyZyTiyk1tGQtBHTDx.jpg',
    genre_ids: [28, 18],
    id: 1511417,
    original_language: 'te',
    original_title: 'Baahubali: The Epic',
    overview:
      'When a mysterious child is found by a tribal couple near a roaring waterfall, they raise him as their own. As he grows, Sivudu is drawn to the world beyond the cliffs, where he discovers the ancient kingdom of Mahishmati, ruled by a cruel tyrant, haunted by rebellion, and bound to his past. What begins as a quest for love soon unravels a legacy of betrayal, sacrifice, and a forgotten prince.',
    popularity: 115.5531,
    poster_path: '/z9YIo2qscyaXYgRqIdRJtND3bw8.jpg',
    release_date: '2025-10-29',
    title: 'Bāhubali: The Epic',
    video: false,
    vote_average: 5.7,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: '/4BtL2vvEufDXDP4u6xQjjQ1Y2aT.jpg',
    genre_ids: [28, 80, 18, 53],
    id: 1419406,
    original_language: 'zh',
    original_title: '捕风追影',
    overview:
      'Macau Police brings the tracking expert police officer out of retirement to help catch a dangerous group of professional thieves.',
    popularity: 108.9707,
    poster_path: '/e0RU6KpdnrqFxDKlI3NOqN8nHL6.jpg',
    release_date: '2025-08-16',
    title: "The Shadow's Edge",
    video: false,
    vote_average: 7.143,
    vote_count: 298,
  },
  {
    adult: false,
    backdrop_path: '/fP6L6V42980QmuoyyGXCmWphwpT.jpg',
    genre_ids: [28, 12, 14],
    id: 1131759,
    original_language: 'ko',
    original_title: '전지적 독자 시점',
    overview:
      'Kim Dok-ja, an ordinary man in his 20s, is the only reader of an obscure web novel titled "Three Ways to Survive the Apocalypse". After having read the last chapter, the novel suddenly becomes reality, and its omnipotent hero Yu Jung-hyeok appears before Kim. As the only person who knows how to survive in this world, Kim and his companions strive to save the world by writing his own, new ending.',
    popularity: 105.772,
    poster_path: '/3R3dXO2nm8JyR5NG7SEfii7RzlV.jpg',
    release_date: '2025-07-23',
    title: 'Omniscient Reader: The Prophecy',
    video: false,
    vote_average: 6.722,
    vote_count: 45,
  },
  {
    adult: false,
    backdrop_path: '/novE5UrqfLIFEMe5QBnjm18GG4E.jpg',
    genre_ids: [28, 80, 53],
    id: 1512623,
    original_language: 'en',
    original_title: 'Risqué',
    overview:
      'Fired from a strip club, a vengeful dancer masterminds a high-stakes heist with fellow strippers to take down the corrupt boss and the men who underestimate them.',
    popularity: 95.7737,
    poster_path: '/h6OsRrDwbspLnKMvlFl57QFDP7d.jpg',
    release_date: '2025-08-01',
    title: 'Risqué',
    video: false,
    vote_average: 7.544,
    vote_count: 45,
  },
];